// app/routes/adventures/$fullId/preview.tsx
import { getPreviewById } from '~/services/adventureService';
import type { Adventure } from '~/config/types';
import AdventurePage from './_components/adventurePage';
import { LoaderFunction, useLoaderData } from 'remix';
import { extractIdAndSlug } from '~/utils/url';

type LoaderDataType = { adventure: Adventure }

export const loader: LoaderFunction = async ({ params, request }): Promise<LoaderDataType> => {
	if (!params.fullId) throw new Error('Could not find fullId url param')

	const { id } = extractIdAndSlug(params.fullId)
	const url = new URL(request.url);
	const adventure = await getPreviewById(id, url.searchParams.get('token'));
	return { adventure }
}

export default () => {
	const { adventure } = useLoaderData<LoaderDataType>()

	return (<AdventurePage adventure={adventure} />)
}

// app/routes/adventures/[id]_[slug]/preview.svelte
<script context="module" lang="ts">
	import type { LoadInput } from '@sveltejs/kit';
	import { getPreviewById } from '$lib/services/adventureService';

	export async function load({ page }: LoadInput) {
		const adventure = await getPreviewById(page.params.id, page.query.get('token'));
		return {
			props: { adventure }
		};
	}
</script>

<script lang="ts">
	import type { Adventure } from '$lib/types';

	import AdventurePage from './_components/adventurePage.svelte';

	export let adventure: Adventure;
</script>

<AdventurePage {adventure} />
